### ISSUE TITLE
SDK cpp on linux 

### ISSUE THREAD

**Issue by FCam1** [qualisys/qualisys_cpp_sdk#3]
Hi,
I want to run a client to receive 6D data under linux so I tried to compile the RTClientExemple but there are some incompatible dependencies like : winsock2.h or TCHAR.H 
Do you have a solution or I have to develop/adapt my own program? Thanks

**Comment by stonfute** [comment]
Hi, 
Did you try CrossPlatform branch ?
[https://github.com/qualisys/qualisys_cpp_sdk/tree/crossplatform](https://github.com/qualisys/qualisys_cpp_sdk/tree/crossplatform)
There's no windows dependency on this branch

**Comment by FCam1** [comment]
Perfect ! Thanks !

**Comment by FCam1** [comment]
"RigidBodyStreaming" compile fine but "RTClientExample" seams to have windows dependencies in input.h like conio.h

**Comment by stonfute** [comment]
If you really need user input you could use [Linux implementation of conio](https://sourceforge.net/projects/linux-conioh/). It's based on `ncurses`.

**Comment by FCam1** [comment]
It seems to be complicated to have "RTClientExample" running on linux but finally "RigidBodyStreaming" does what I want, so everything is fine!
Thanks

**Comment by mlveggo** [comment]
Agree that it will take a bit of effort to get that example cross platform. We will probably make more specific usage examples in the future. Anything you want to contribute with just do a pull request.

**Comment by mlveggo** [comment]
Now the crossplatform branch has been merged into the master branch
