### ISSUE TITLE
How to get camera time from streaming packet?

### ISSUE THREAD

**Issue by cnicho35** [qualisys/qualisys_cpp_sdk#36]
I am using the RigidBodyStreaming example and I would like to add the ability to get the camera absolute timestamp with the 6DOF data. 

If I run the following line, it gives me some other timestamp; I believe it is the running time rather than absolute camera time.
unsigned long long timestamp = rtPacket->GetTimeStamp();

Is there anyway to get the camera Unix time that is available in the QTM GUI software with the API?

Any help would be greatly appreciated!

**Comment by adv4ncr** [comment]
I would be interested too.

**Comment by cnicho35** [comment]
Figured it out... need to tell it to stream timecode in StreamOptions:

`
                if (!rtProtocol.StreamFrames(CRTProtocol::RateAllFrames, 0, udpPort, NULL, "6d timecode")) // stream 6DOF bodies and timecode
`

Then later...

```
                    rtPacket->GetTimecodeCameraTime(cameraTime);

                    std::cout << "Camera Time: " << cameraTime << std::endl;
```

**Comment by adv4ncr** [comment]
Thanks for following up on this topic. Unfortunately, I was unable to get camera time codes with the code provided. Are there any QTM settings to make it work? Do you also run the RT capture with delayed exposure?

**Comment by cnicho35** [comment]
@adv4ncr Are you using the cpp sdk in addition to the QTM GUI? If so, you'll have to use the GUI settings window to turn on camera timestamps: 
![image](https://github.com/qualisys/qualisys_cpp_sdk/assets/60717102/7aeefd71-7288-4bd4-8bc6-f5f50dc4966d)

If you aren't using the GUI, you'll have to add more RTClient code for turning on the camera timestamp.

**Comment by adv4ncr** [comment]
What cameras and QTM version are you using? I can't find this "timestamp" setting in 2022.2. with Arqus A5 cameras.

I am also interested in your second point: how do you use QTM headless? I contacted Qualisys about this once with a negative response.

**Comment by cnicho35** [comment]
I can't remember which version we are using but I think it's around 2022.2. We also are using Arqus cameras.

The timestamp is in the record options. You have to set it to use "camera time" but I can't remember which tree selection that is in. Maybe camera options?

Also, you can't run the QTM headless but you can control the QTM GUI with the SDK. The QTM must be running on the windows PC and it basically creates a server that you can connected to with a client. The client is able to control the QTM software (but it must be running on the PC and therefore is not headless). The RTClientExample shows how you can do that.
