### ISSUE TITLE
clang warning on redundant code

### ISSUE THREAD

**Issue by e4lam** [qualisys/qualisys_cpp_sdk#38]
When compiling the latest code with clang, a warning is emitted:
```
RTProtocol.cpp:1016:13: warning: address of array 'pResponseStr' will always evaluate to 'true' [-Wpointer-bool-conversion]
        if (pResponseStr && strlen(pResponseStr) > 0)
            ^~~~~~~~~~~~ ~~
1 warning generated.
```
Notice that in the other functions in there, the extraneous nullptr check was already removed. eg. at https://github.com/qualisys/qualisys_cpp_sdk/blob/fa5bd0711329e6b30360782252c42c2cd47b07e5/RTProtocol.cpp#L685C5-L685C30

**Comment by Henrik-Norgren** [comment]
Indeed. I assume the old `nullptr` checks meant to check for `'\0'` but checked the address of the array instead. Will remove it.
