### ISSUE TITLE
Large git repo size

### ISSUE THREAD

**Issue by whoenig** [qualisys/qualisys_cpp_sdk#5]
When cloning this repository nearly 700MB of disk space are used.

```
$ git clone https://github.com/qualisys/qualisys_cpp_sdk.git
Cloning into 'qualisys_cpp_sdk'...
remote: Enumerating objects: 198, done.
remote: Counting objects: 100% (198/198), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 206 (delta 95), reused 183 (delta 82), pack-reused 8
Receiving objects: 100% (206/206), 114.45 MiB | 2.39 MiB/s, done.
Resolving deltas: 100% (96/96), done.
Checking out files: 100% (41/41), done.
```
Please reduce the size by:
1. Deleting the temporary files in the ".vs" subfolders
2. Cleaning the history of the large unneeded blobs, e.g., by using https://rtyley.github.io/bfg-repo-cleaner/

Background: I would like to include this as a submodule in https://github.com/whoenig/motioncapture_ros, a ROS driver that supports multiple motion capture systems.

**Comment by mlveggo** [comment]
Agree. It was mistake to include visual studio environment files. We will shrink the repo.

**Comment by mlveggo** [comment]
We have now reduced it in size.
