### ISSUE TITLE
Error reporting from `SetVersion`

### ISSUE THREAD

**Issue by tbolin** [qualisys/qualisys_cpp_sdk#9]
The error string from `SetVersion` will be empty if `SendCommand` gets a PacketError in response from the server. 
https://github.com/qualisys/qualisys_cpp_sdk/blob/a7fab1371b5e0d7c1d843032079c03c6821d9c44/RTProtocol.cpp#L247-L281
`SendCommand` will return `false` on an error packet. Therefore the error handling in the first if statement is unreachable. 
On an error packet, `SendCommand` does not copy the error message to the error string (it's put into `pResponseStr`). Since the error string is empty, the else clause will just set the error string to `"Send Version failed. ."`, without giving any further information about the error.

**Comment by nilzilch** [comment]
I have fixed the bug in the SendCommand error message. Just completed a new pull request containing the fix.
